feat: added HTTP capability
deislabs/spiderlightning pull request #143
Opened 2022-08-02 02:26 UTC by Mossaka

This PR adds HTTP server capability to `slight`, it's main contributions are
1. `wit/http-api.wit` HTTP API WIT file. 
1. `/crates/http-api` adds a host implementation for HTTP server
2. `/crates/http-handler-macro` adds macro for registering HTTP handler functions
3. `examples/http-demo` adds an guest example for using HTTP WIT

It will close #96

2022-08-09 23:11 UTC, Mossaka commented on crates/http/Cargo.toml
> +doctest = false
We have some unittests in `http` crate. I don't think we should toggle off `test`.

2022-08-09 23:13 UTC, Mossaka commented on crates/http/src/lib.rs
> +pub struct RouterProxy {
I guess it's fine for now. both `http` and `events` do not have multiple components.

2022-08-09 23:13 UTC, Mossaka commented on crates/http/src/lib.rs
> +    _base_uri: String,
Not used anywhere.

2022-08-09 23:58 UTC, Mossaka commented on .gitignore
> +.idea
generated files for other IDEA IDE

2022-08-11 18:15 UTC, danbugs requested changes
mostly, looking good to me~ just bringing back a couple of resolved items and small nits

2022-08-11 18:15 UTC, danbugs commented on crates/http/src/lib.rs
> +pub struct RouterProxy {
I meant mostly for convention of calling these structures `SomethingInner`~ up to u, tho

2022-08-15 22:00 UTC, Mossaka commented
I just pushed a commit that adds `put` `post` and `delete` methods to our http-handler.

2022-08-17 05:58 UTC, Mossaka commented on crates/http/src/lib.rs
> +pub struct RouterProxy {
Renamed~ 
\

2022-08-17 06:00 UTC, Mossaka commented on crates/http/src/lib.rs
> +        let clone = server.clone();
done~

2022-08-17 23:02 UTC, danbugs approved these changes
LGTM~ I think you just forgot to address one of the comment typo nits, I brought up!

2022-08-18 23:57 UTC, Mossaka commented on crates/http-api/src/lib.rs
> +/// A owned http_handler::HeadersParam
I will resolve this in `http-builder` branch

2022-08-18 23:58 UTC, merged